openapi: "3.0.1"
info:
  title: "dan-cifar-api"
  description: "test"
  version: "2021-04-27T01:40:53Z"
servers:
- url: "https://8qut1q69xf.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/demo"
paths:
  /caltech256:
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /predictimages:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /cifar10:
    post:
      parameters:
      - name: "Content-Type"
        in: "header"
        schema:
          type: "string"
      - name: "Accept"
        in: "header"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /test:
    get:
      parameters:
      - name: "Content-Type"
        in: "header"
        schema:
          type: "string"
      - name: "Accept"
        in: "header"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      parameters:
      - name: "Content-Type"
        in: "header"
        schema:
          type: "string"
      - name: "Accept"
        in: "header"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /:
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
